=== GermanPodlesskiy/EpamLab/target/classes/client.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="clients" type="clientsType"/>
    <xs:complexType name="tableType">
        <xs:sequence>
            <xs:element type="xs:integer" name="number"/>
            <xs:element type="xs:boolean" name="is-free"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="menu-itemType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:double" name="price"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="chosen-menu-itemsType" mixed="true">
        <xs:sequence>
            <xs:element type="menu-itemType" name="menu-item" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientType">
        <xs:sequence>
            <xs:element type="xs:integer" name="id"/>
            <xs:element type="xs:string" name="first-name"/>
            <xs:element type="xs:string" name="last-name"/>
            <xs:element type="xs:double" name="money"/>
            <xs:element type="tableType" name="table" minOccurs="0"/>
            <xs:element type="chosen-menu-itemsType" name="chosen-menu-items"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="clientsType">
        <xs:sequence>
            <xs:element type="clientType" name="client" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== GermanPodlesskiy/EpamLab/src/main/resources/client.xml
<?xml version="1.0" encoding="UTF-8"?>
<clients xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xs:noNamespaceSchemaLocation="client.xsd">
    <client>
        <id>1</id>
        <first-name>FirstName1</first-name>
        <last-name>LastName1</last-name>
        <money>1000</money>
        <table>
            <number>1</number>
            <is-free>true</is-free>
        </table>
        <chosen-menu-items>
            <menu-item>
                <name>Soup</name>
                <price>100</price>
            </menu-item>
            <menu-item>
                <name>salad</name>
                <price>70</price>
            </menu-item>
        </chosen-menu-items>
    </client>
    <client>
        <id>4</id>
        <first-name>FirstName4</first-name>
        <last-name>LastName4</last-name>
        <money>800</money>
        <chosen-menu-items/>
    </client>
    <client>
        <id>3</id>
        <first-name>FirstName3</first-name>
        <last-name>LastName3</last-name>
        <money>700</money>
        <table>
            <number>3</number>
            <is-free>true</is-free>
        </table>
        <chosen-menu-items>
            <menu-item>
                <name>Soup</name>
                <price>100</price>
            </menu-item>
            <menu-item>
                <name>meat</name>
                <price>300</price>
            </menu-item>
            <menu-item>
                <name>salad</name>
                <price>70</price>
            </menu-item>
        </chosen-menu-items>
    </client>
    <client>
        <id>2</id>
        <first-name>FirstName2</first-name>
        <last-name>LastName2</last-name>
        <money>1100</money>
        <table>
            <number>2</number>
            <is-free>true</is-free>
        </table>
        <chosen-menu-items>
            <menu-item>
                <name>Soup</name>
                <price>100</price>
            </menu-item>
            <menu-item>
                <name>salad</name>
                <price>70</price>
            </menu-item>
        </chosen-menu-items>
    </client>
    <client>
        <id>5</id>
        <first-name>FirstName5</first-name>
        <last-name>LastName5</last-name>
        <money>100</money>
        <chosen-menu-items/>
    </client>
</clients>
